Docker image building
rilldata/rill-developer pull request #1436
Opened 2022-12-13 15:15 UTC by himadrisingh

2022-12-13 15:17 UTC, himadrisingh commented on .github/workflows/cli-release.yml
> +              release ${NIGHTLY} --snapshot
```suggestion
              release ${NIGHTLY}
```

2022-12-14 14:58 UTC, begelundmuller requested changes
- I think we can get rid of `entrypoint.sh` file. Doesn't seem like something we use/do anymore.
- Let's copy the `rill` binary to `/rill`, not `/app/rill` (or maybe to a `bin` folder?)
- For the entrypoints, how about this? (Always forget the Docker mechanics for these, let me know if it looks bad):

```
ENTRYPOINT /rill
CMD /rill start
```
- Should we let the default workdir be `/project`? So people should mount their artifacts there if they have an existing project. (Or do you have a more idiomatic suggestion, maybe `/data`?) (People can always override by passing `--project /path/to/code` anyway)

2022-12-15 13:56 UTC, himadrisingh commented on .goreleaser.yaml
> +      - scripts/entrypoint.sh
```suggestion
```

2022-12-15 14:25 UTC, kaspersjo requested changes

2022-12-15 14:25 UTC, kaspersjo commented on Dockerfile
We need to `apt-get install -y ca-certificates` for the bucket and HTTP source connections to work.

2022-12-15 14:31 UTC, himadrisingh commented on Dockerfile
> +WORKDIR /project
```suggestion
RUN apt-get install -y ca-certificates
WORKDIR /project
```

2022-12-16 08:52 UTC, begelundmuller approved these changes
LGTM

2022-12-16 10:59 UTC, merged