Add running status spinner to app
rilldata/rill-developer pull request #1617
Opened 2023-01-17 11:58 UTC by djbarnwal

Closes #1567

2023-01-17 12:14 UTC, AdityaHegde commented on web-local/src/lib/http-request-queue/HttpRequestQueue.ts
> +    appQueryStatusStore.set(!!this.nameHeap.peek()?.name);
This should be based on `activeCount`. When we pop from heap we just trigger the network call. So the spinner should be spinning when `activeCount` is not 0.

2023-01-18 04:15 UTC, hamilton requested changes
Thanks for getting this together so quickly @djbarnwal! I'm glad this was fast to implement. I left a few small changes; feel free to address, dismiss my review, and merge when done with the changes.

2023-01-18 04:15 UTC, hamilton commented on web-local/src/lib/components/workspace/core/WorkspaceHeader.svelte
> -    {#if showStatus}
I'm finding that this icon seems to jump around quite a bit so I'm not always sure where it is between views. Can we keep the spinner on the right side? that way it remains in a consistent location for the time being. I suspect we'll probably change its location for #1620.

2023-01-18 04:15 UTC, hamilton commented on web-local/src/lib/components/workspace/core/WorkspaceHeaderStatusSpinner.svelte
> +<div class="mr-2">
I think we should probably keep this spacing in the parent component rather than here. Otherwise this affects reuse.

2023-01-18 04:15 UTC, hamilton commented on web-local/src/lib/components/workspace/core/WorkspaceHeaderStatusSpinner.svelte
>      <Tooltip alignment="center" distance={16} location="left">
```suggestion
    <Tooltip alignment="center" distance={8} location="left">
```

16 feels a little too far from the icon given the other header spacing

2023-01-18 10:59 UTC, AdityaHegde approved these changes

2023-01-18 11:05 UTC, merged