Create `readonly` UI
rilldata/rill-developer pull request #1625
Opened 2023-01-17 23:17 UTC by ericpgreen2

This PR provides that when `rill start --readonly`:
- Sources and Models are hidden from the navigation sidebar. Any direct navigation to these pages results in a 404.
- The `Edit Metrics` button is hidden from the Dashboard workspace

2023-01-18 05:00 UTC, hamilton requested changes
Thanks for such a speedy PR @ericpgreen2! It works well for the task at hand and with minimal code changes. Left one change about hiding the + button for the dashboard nav in readonly mode.

2023-01-18 07:07 UTC, ericpgreen2 commented on web-local/src/lib/components/navigation/Navigation.svelte
>          <MetricsDefinitionAssets />
Ah good catch, thanks. Fixed.

2023-01-18 17:32 UTC, hamilton commented
Noted over Slack that we should probably hide some of the bullets on the splash page in `readonly` mode as well.

2023-01-18 20:50 UTC, hamilton approved these changes
lgtm. If a metrics config is invalid, it does still show up in the sidebar in readonly mode. Could we get it filtered out there in `readonly` settings?

Feel free to merge once that's addressed.

2023-01-19 03:19 UTC, ericpgreen2 commented
> lgtm. If a metrics config is invalid, it does still show up in the sidebar in readonly mode. Could we get it filtered out there in `readonly` settings?
> 
> Feel free to merge once that's addressed.

I think that's addressed by the CLI's `--strict` flag. Since we're going to run `rill start --readonly --strict`, if any artifact fails to validate, the process will exit with a fatal error.

2023-01-19 06:53 UTC, merged