update model workspace CTA to point to pre-existing dashboard(s) instead of "create new dashboard"
rilldata/rill-developer pull request #1626
Opened 2023-01-18 02:56 UTC by hamilton

2023-01-18 10:39 UTC, djbarnwal requested changes
I am unable to create a dashboard out of a model with no time dimensions. Apart from that looks good, have added a few nit comments.

2023-01-18 10:39 UTC, djbarnwal commented on web-common/src/features/models/workspace/CreateDashboardButton.svelte
> +  $: timestampColumns = selectTimestampColumnFromSchema(model?.schema);
We don't need this variable (see below)

2023-01-18 10:39 UTC, djbarnwal commented on web-common/src/features/models/workspace/CreateDashboardButton.svelte
> +    <ResponsiveButtonText {collapse}>Create Dashboard</ResponsiveButtonText>
There is no tooltip content for the Create Dashboard button. 
This is also present in main but probably best to handle in this PR.

![image](https://user-images.githubusercontent.com/4402679/213146895-8a5250cf-1987-48fc-a20e-3d86d2b4f44f.png)

2023-01-18 10:39 UTC, djbarnwal commented on web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
> +  );
We can move this to `svelte-query/dashbords.ts` (which will be later moved to `features/dashboards/selectors.ts`)

2023-01-18 10:39 UTC, djbarnwal commented on web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
> +              <IconSpaceFixer pullLeft pullRight={width < 800}
Nit: we can move these multiple `width < 800` inside the script tag.

2023-01-19 10:01 UTC, djbarnwal approved these changes

2023-01-20 18:39 UTC, ericpgreen2 commented
Code looks good.

Experience-wise, I think it'd be good to retain a CTA to create a new dashboard, alongside the CTA to go to an existing one. Scott says it's a common pattern for our customers to have multiple dashboards for one model (where often fwiw each dashboard is a different subset of measures/dimensions). I know it's _technically_ possible to still create two dashboards, but it's not obvious.

2023-01-20 19:50 UTC, hamilton commented
It's a good point re: multiple dashboards on one model, but I think this will be the way we meet the underlying need going forward. There are many other ways to solve this issue that don't look like child dashboards, including RBAC and other affordances that aren't in scope for Rill Developer. Given that this is not a one-way door I would prefer we merge as-is and we can readdress later. Thanks for the review @ericpgreen2!

2023-01-20 19:51 UTC, merged