adding quotes to alter view
rilldata/rill-developer pull request #1631
Opened 2023-01-18 15:08 UTC by rakeshsharma14317

2023-01-19 15:50 UTC, AdityaHegde approved these changes

2023-01-23 13:52 UTC, begelundmuller reviewed
This looks good.

I'm wondering if we've caught everything. Have you done an experience pass? Please try to build this and create a project with spaces in a source, model and dashboard name. And check that also all profiling queries run correctly.

2023-01-26 10:44 UTC, begelundmuller approved these changes

2023-01-26 11:04 UTC, begelundmuller requested changes
You forgot to merge in your changes. It no longer uses `%` for the names

2023-01-26 15:45 UTC, begelundmuller approved these changes

2023-01-26 15:45 UTC, merged