add new time range and grain configs
rilldata/rill-developer pull request #1722
Opened 2023-02-08 04:48 UTC by pjain1

2023-02-09 18:25 UTC, pjain1 commented
@begelundmuller can you have a look ? Thanks

2023-02-10 05:09 UTC, pjain1 commented
Using https://github.com/senseyeio/duration library to validate ISO duration which is MIT licensed, hope this is fine.

2023-02-10 23:12 UTC, begelundmuller requested changes
Just some small comments, otherwise this looks great

2023-02-13 05:03 UTC, pjain1 commented on go.mod
> +	github.com/senseyeio/duration v0.0.0-20180430131211-7c2a214ada46
copied

2023-02-13 05:04 UTC, pjain1 commented on runtime/services/catalog/artifacts/yaml/objects.go
> +	apiMetrics.DefaultTimeGrain = getTimeGrainEnum(metrics.DefaultTimeGrain)
done

2023-02-13 15:27 UTC, begelundmuller approved these changes

2023-02-13 15:27 UTC, merged