Calendly integration for dashboard publish
rilldata/rill-developer pull request #1756
Opened 2023-02-15 05:53 UTC by AdityaHegde

2023-02-15 19:21 UTC, ericpgreen2 commented on web-common/src/features/dashboards/workspace/DashboardHeader.svelte
> +        <Button on:click={openCalenderly} type="primary">Publish</Button>
This should be behind the `isEditableDashboard` flag too. The read-only dashboards will be hosted/published already.

2023-02-15 19:23 UTC, ericpgreen2 commented on web-common/src/features/dashboards/workspace/DashboardHeader.svelte
> +  function openCalenderly() {
typo: "openCalendly" not "openCalenderly"

2023-02-15 19:26 UTC, ericpgreen2 commented on web-common/src/features/dashboards/workspace/DashboardHeader.svelte
> +    <PanelCTA>
This triggers a `svelte-check` error: "Property 'side' is missing in type '{}' but required in type '{ side: \"left\" | \"right\"; }'."

2023-02-15 19:40 UTC, ericpgreen2 commented
Regarding the telemetry changes, I'll let @magorlick do the thorough review, but one idea is to add a schema version to each event type.

2023-02-16 12:11 UTC, AdityaHegde commented
Thanks @ericpgreen2 . Good point about the schema. Feel like it fits the other PR https://github.com/rilldata/rill-developer/pull/1760 more than this.

2023-02-17 06:28 UTC, ericpgreen2 commented
Oh I hadn't seen 1760 – agreed.

I'll approve from the code standpoint, but I imagine @magorlick wants to review UX.

2023-02-17 06:28 UTC, ericpgreen2 approved these changes

2023-02-19 21:31 UTC, magorlick commented on web-common/src/components/modal/dialog/Dialog.svelte
> +        width = "calc(100% - 2*var(--header-height))";
```suggestion
        xDimClasses = "w-4/5 md:w-3/5 xl:w-1/2 2xl:w-2/3";
```

2023-02-19 21:31 UTC, magorlick commented on web-common/src/components/modal/dialog/Dialog.svelte
> +        height = "calc(100% - 2*var(--header-height))";
```suggestion
        yDimClasses = "h-4/5";
```

2023-02-19 21:32 UTC, magorlick requested changes
Thank you for these changes @AdityaHegde ! The functionality is great, we some refinement needed for the experience and a telemetry check.

**[p0]** Please update copy for tool tip for publish button to read, ***“Schedule time to chat with Rill about early access to hosted dashboards.”***

**[p0]** Make the modal window tighter around the calendly embed. It should have no more than 60px of padding around the embed at all sizes. I left a suggestion that might work, but I am not sure what else we are using "full" for in Dialog.svelte.

**[p0]** I couldn’t see telemetry for the publish button successfully send. Not sure if that should be what is happening here. 

Internal notes here: https://www.notion.so/rilldata/1756-calendly-for-publish-a9747bc61feb4f3faf1ed9bb7084f52e

2023-02-20 05:38 UTC, AdityaHegde commented
@magorlick Have made the changes you suggested. I am not an expert in css, so lemme know if it looks good.

The telemetry is firing for me. It fires when you open the calendly modal and after you have successfully scheduled a meeting. Lemme know if this works.

2023-02-20 20:34 UTC, magorlick commented
@AdityaHegde , I can see the start and success telemetry now and the felt experience is better. Very close!

The calendly link is no longer correct. Please update to the one I am DMing you, also in our docs. :)

2023-02-21 09:33 UTC, AdityaHegde commented
@magorlick Updated the link.

2023-02-21 16:23 UTC, magorlick approved these changes
lgtm!

2023-02-21 16:23 UTC, merged