Adding selected measure and dimension to the state
rilldata/rill-developer pull request #1941
Opened 2023-03-15 13:46 UTC by AdityaHegde

closes #1905

2023-03-15 21:25 UTC, hamilton requested changes
Thanks for the PR!

### bits of state
All the additional state pieces appear to work as needed. I made a suggestion to rename `time_granularity` to `time_grain` in the dash since that's what we actually are calling it. Probably the right time to align on the terminology.


### back button dynamics
Unfortunately, the back button only sort of works with this PR. The forward button is not preserved and I have to click twice to make the back button take effect. We have two options to fix this:

*use the history API to make sure that the actual querystring state is navigable with a back + forward button.* This will require some manual work to make sure it works as expected. It also means we need to de-duplicate history here, since I think that's what's happening w/ the current behavior where I need to click twice to have it take effect.

*Move to a pure route-based version of the protobuf message*, and version it, using sveltekit's routing to take care of the capture. After chatting with @medriscoll, it seems like it might make more sense for us to _embed the protobuf into the route itself_ rather than rely on querystrings. 

The URL would then look like `<base>/dashboards/<dashboardName>/v1--<protobuf>`. Taking this approach means we could probably version in a specific route. What we get out of this is that in theory the back / forward button works by default. It would mean we have to create some routes & get the logic right, but it will surely be more robust than trying to get the history semantics right. See [advanced routing docs](https://kit.svelte.dev/docs/advanced-routing) for more information. I think this means the route itself would look like `/dashboards/[name]/v1--[state]`. We would have to figure out:
- what happens when no filters are selected. I think we still keep `/dashboards/[name]` since it's identical to `/dashboards/[name]/v1--[state]` with the exception of `[state]`.
- when I go from a no-filter selected -> a filter selected (or some state changed), make sure it doesn't completely refresh the page.

---

Happy to talk about how we handle this tomorrow if that'll help.

2023-03-16 03:47 UTC, AdityaHegde commented on web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
> +    if (measureFormatSpec) {
UI broke without this check

2023-03-16 03:49 UTC, AdityaHegde commented on proto/rill/ui/v1/dashboard.proto
> +  rill.runtime.v1.TimeGrain time_granularity = 3;
Merged main and fixed

2023-03-16 03:49 UTC, AdityaHegde commented on web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
> +   * Selected time rage
Merged main and regenerated

2023-03-16 22:44 UTC, hamilton commented
@AdityaHegde fixed a few things in this PR:
- the charts now tween on back button. There was an intermediate step where you were setting the `startValue` and `endValue` to `undefined` without checking first to see if there were valid dates to set.
- I fixed a weird render bug where if I select items in the leaderboard, for some reason they were not propagating the active state on back / forward button.

2023-03-16 22:51 UTC, hamilton commented on proto/rill/ui/v1/dashboard.proto
> +  // Selected time granularity
```suggestion
  // Selected time grain
```

2023-03-16 22:53 UTC, hamilton approved these changes
lgtm. I added a few changes to the styling to make it work correctly.

We'll need to add tests for `fromProto` / `toProto`, but given that we need this PR to land before we can finish #1942, let's get this in.

2023-03-16 22:54 UTC, merged