Queries observability: metrics and tracing for http/grpc
rilldata/rill-developer pull request #1950
Opened 2023-03-16 15:15 UTC by egor-ryashin

Closes https://github.com/rilldata/rill-developer/issues/1835

2023-03-16 17:59 UTC, begelundmuller requested changes
Also, can we reduce the apm setup to one docker-compose file by inlining the `otel-collector-config.yaml` and `prometheus.yaml` files? Such as the example here: https://github.com/open-telemetry/opentelemetry-go/blob/3a40e65a38db12d8d1b1a313ff78b27452b2accc/example/otel-collector/k8s/otel-collector.yaml#L24

2023-03-16 17:59 UTC, begelundmuller commented on apm/docker-compose.yaml
> +      - "8889:8889" # Prometheus exporter metrics
Can we use less common ports here? E.g. Jupyter uses 8888, which I often start

2023-03-16 17:59 UTC, begelundmuller commented on apm/docker-compose.yaml
> +      - "9090:9090"
We use port 9090 for the gRPC service on admin, so to prevent collisions, can we use another port?

2023-03-16 17:59 UTC, begelundmuller commented on runtime/server/server.go
> +func InitOpenTelemetry() error {
Should this not integrate with the server lifecycle? E.g. how will this work in testing when there are multiple servers? How will the exporters be closed/flushed correctly when the process stops?

2023-03-16 17:59 UTC, begelundmuller commented on runtime/server/server.go
> +	}
Env vars should be parsed in `cli/cmd/runtime/start.go` into the `Config` and passed down from there when possible

2023-03-16 17:59 UTC, begelundmuller commented on runtime/server/server.go
> +	return nil
Please add some brief comments describing what happens here

2023-03-16 17:59 UTC, begelundmuller commented on cli/pkg/local/app.go
> +			mux.Handle("/local/track", runtimeserver.OtelHandler(a.trackingHandler(inf)))
These are static endpoints, we can remove otel tracking here. The runtime endpoints are the only ones that really matter

2023-03-23 10:37 UTC, egor-ryashin commented
> Also, can we reduce the apm setup to one docker-compose file by inlining the otel-collector-config.yaml and prometheus.yaml files? Such as the example here: https://github.com/open-telemetry/opentelemetry-go/blob/3a40e65a38db12d8d1b1a313ff78b27452b2accc/example/otel-collector/k8s/otel-collector.yaml#L24

It's K8s configs (not Docker Compose).

2023-04-16 14:42 UTC, begelundmuller approved these changes

2023-04-16 14:43 UTC, merged

2023-04-16 15:03 UTC, begelundmuller commented
As part of the changes, I removed `otelzap` because it would not emit any logs unless there's a span present, which is not great since lots of our logging runs outside of requests.

I did some research, and found lots of useful context in this thread: https://github.com/uber-go/zap/issues/654. I used that as inspiration to add `observability.ZapCtx` as a helper for adding `trace_id` and `span_id` fields on the normal Zap. This will not add the logs as events on the traces, though – if we want to do that, the thread recommends using a custom Zap exporter (but it sounds like DataDog makes it easy to correlate traces and logs using `trace_id`, so it might not be needed).

2023-04-17 14:00 UTC, begelundmuller commented
> As part of the changes, I removed `otelzap` because it would not emit any logs unless there's a span present.

@egor-ryashin pointed out this is not correct. I'm hesitant to replace Zap with `otalzap` for a few other reasons (like that it doesn't seem very mature), but let's keep an eye on it and reconsider in the future.