Measure and dimension visibility selection in dashboard
rilldata/rill-developer pull request #2034
Opened 2023-04-05 20:00 UTC by bcolloran

will fix #308 
see https://www.notion.so/rilldata/Ability-to-hide-measures-and-dimensions-from-the-dashboard-f416bfaddda74e5285ec8bc33161a2c0

Note from @hamilton: this PR will only implement the components for showing & hiding the measure dimensions. As of merging, we'll still need to do the following:
- ensure a unique `name` field exists for all measures & dimensions. This is backend work on the runtime.
- capture state for the shown / hidden measures & dims in the dashboard state (and then the actual stateful URL).
- auto-generate dashboards should template in a `name` field for each dimension (once we have `name` in for dimensions).

cc @begelundmuller for backend parts

2023-04-10 18:32 UTC, bcolloran commented
@hamilton this is ready for an experience pass

@AdityaHegde, can you do code review and also wire up whatever is needed to capture the visibility state of the measures and dimensions in the URL? Hamilton said that he thought that would be pretty quick and easy for you, lmk if I can help

2023-04-11 13:05 UTC, hamilton requested changes
Thanks for the PR! The functionality is great and the code is very clean. 

I left a few comments on both design and implementation below. The most obvious one is moving away from the bitmap. I think this may cause some issues down the line as noted in the comment.

If you can fix that first, then Aditya will jump in and add state to this when he begins his workday tomorrow.

2023-04-11 13:05 UTC, hamilton commented on web-common/src/features/dashboards/leaderboard/LeaderboardMeasureSelector.svelte
> +      <div class="whitespace-nowrap">sorted by</div>
I found this text a bit confusing.

`All dimensions sorted by total sales` reads like I sort the leaderboard cards themselves, not the values within them. Not sure I have a solution for this.

2023-04-11 13:05 UTC, hamilton commented on web-common/src/features/dashboards/leaderboard/LeaderboardMeasureSelector.svelte
> +      <SeachableFilterButton
Could we possibly line up these selectors with the text in the first leaderboard in the x direction?

<img width="386" alt="Screen Shot 2023-04-11 at 6 00 37 AM" src="https://user-images.githubusercontent.com/95735/231170339-445b6f71-cec0-44a7-b831-71d3f9a978b9.png">

2023-04-11 13:05 UTC, hamilton commented on web-common/src/features/dashboards/leaderboard/LeaderboardMeasureSelector.svelte
> +      <div class="whitespace-nowrap">sorted by</div>
We could change this to "showing top values by [selection]"

2023-04-11 13:06 UTC, hamilton commented on web-common/src/components/searchable-filter-menu/SearchableFilterDropdown.svelte
> +  $: allToggleEvt = numSelected === 0 ? "selectAll" : "deselectAll";
I think we're not 100% consistent here, but I tend to prefer `select-all` kebab casing for component events, and this is what's most dominant in the code I think.

2023-04-14 00:03 UTC, bcolloran commented on web-common/src/components/data-graphic/marks/MultiMetricMouseoverLabel.svelte
> +      if (container) {
added this condition to fix a bug I was hitting where `container` was not present at the time the setTimeout was called

2023-04-14 00:15 UTC, bcolloran commented
@hamilton all comments addressed, though I left in FIXMEs for the entity keys. If that is expected to land next week, recommend we hold off on final review on this branch until that PR lands, at which point I can  merge in those changes and clear the FIXMEs.

2023-04-21 22:16 UTC, bcolloran commented
@hamilton -- updating my previous recommendation, I think we should merge this PR as-is (pending any changes needed from review) rather than waiting for an entity key solution to fully land. This PR does add nice incremental functionality in it's current state, and even if the serialization to stateful URL lands in a subsequent PR, I think this will still an improvement.

Once @AdityaHegde and/or @begelundmuller have finalized the entity key it should be a simple matter to swap out the items used as keys in `visibleMeasureKeys` and `visibleDimensionKeys` in `dashboard-stores.ts`.

@hamilton  what do you think? Can you do another review pass and merge?

2023-04-25 19:45 UTC, bcolloran commented
@AdityaHegde  can you review this PR?

We should land this functionality, then you can follow up with a second PR to make sure the visibility state is synced in the URL -- this will be valuable even without that final bit of functionality, and that should be a fast and easy follow up hopefully.

2023-04-27 20:53 UTC, hamilton approved these changes

2023-04-27 21:32 UTC, merged