separate file logger
rilldata/rill-developer pull request #2461
Opened 2023-05-19 05:42 UTC by k-anshul

2023-05-22 17:25 UTC, nishantmonu51 commented
tested and works as expected, Will look at more detailed logs.

2023-05-23 09:35 UTC, nishantmonu51 approved these changes
LGTM, have tested it on my local rill setup as well.

2023-05-24 10:33 UTC, begelundmuller requested changes
1. Also missing `observability.ZapCtx(ctx)` in most logs
2. Add `With(zap.String("instance", instanceID), zap.String("driver", "duckdb"))` or something similar to the logger used in DuckDB (add once so it's in all log messages, including those on the logger passed down to the connectors)

2023-05-24 10:33 UTC, begelundmuller commented on runtime/connectors/blob/blobdownloader.go
> +				it.logger.Info("download complete", zap.String("object", obj.obj.Key), zap.Float64("took_seconds", duration.Seconds()))
Use `zap.Duration` instead, and make field `duration` instead of `took_seconds`

2023-05-24 10:33 UTC, begelundmuller commented on runtime/drivers/duckdb/connectors.go
> +		c.logger.Info("ingested files", zap.String("source", source.Name), zap.Strings("files", files), zap.Int64("bytes_ingested", size), zap.Float64("took_seconds", time.Since(st).Seconds()))
Use `zap.Duration`

2023-05-24 14:04 UTC, begelundmuller approved these changes

2023-05-24 14:05 UTC, merged