adds filter pills
rilldata/rill-developer pull request #809
Opened 2022-08-19 20:28 UTC by hamilton

2022-08-23 13:13 UTC, hamilton commented on src/lib/components/chip/core/Chip.svelte
> +<!-- Chips have three areas:
```suggestion
<!-- Chips have two areas:
```

2022-08-23 14:26 UTC, magorlick commented
Really appreciating this feature it is so much clearer which filters are being applied to the dashboard.  A few experience notes:
1) it took me a minute to figure out how to clear all of the filters in one click.  I was missing that feature.  Is there any way we could make that a little bit more clear without having to hover over the filter icon?  The tool tip says I need to press shift and then click the icon, but it also works without holding shift.
2) if I deselect some of the selected values the filter chip and values stay, however if I deselect all of them the whole thing disappears without me clicking outside of it or closing it.  My preferred experience would keep the chip there with the prior selections until I click outside of the menu.

2022-08-23 19:27 UTC, bcolloran requested changes
looks good. couple small change requests

2022-08-23 19:27 UTC, bcolloran commented on src/lib/components/modeler/ModelerToMetricsButton.svelte
>      DerivedModelStore,
vscode tells me:

`This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.ts(1371)`

2022-08-23 19:27 UTC, bcolloran commented on src/routes/_surfaces/workspace/explore/filters/Filters.svelte
> +        <div animate:flip={{ duration: 200 }}>
I think this section is a little harder to read than it needs to be-- how about constructing an array that contains only the data needed for the display the code section above. That'd simplify the `{#if prunedValues?.length && $dimensions?.length}` to one check and the two `@const`s could be removed here (clarify focus on the rendering)

2022-08-24 03:38 UTC, hamilton commented on src/lib/components/chip/core/RemoveChipButton.svelte
> +  ) as Writable<boolean>;
Generally agree, but this doesn't really apply when it comes to components needing to communicate with other components for transient UX state (which is what this specific case is – a parent element needs to suppress its tooltip).

2022-08-24 14:52 UTC, magorlick approved these changes
Thank you for these changes - this experience looks great!

2022-08-24 15:28 UTC, merged